apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkjava-deployment
  labels:
    app: sparkjava
  namespace: sparkjava
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sparkjava-deploy
  template:
    metadata:
      labels:
        app: sparkjava-deploy
    spec:
      containers:
      - name: sparkjava
        image: 003669760817.dkr.ecr.ap-northeast-1.amazonaws.com/tomcat:22
        ports:
        - containerPort: 8080






        